Hackathon/urls.py
from django.contrib import admin
from django.contrib.auth import urls
from django.urls import path,include
from Account.views import profile,signup,signin,error,esignin
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/',profile,name='profile'),
    path('error/',error,name='error'),
    path('esignin/',esignin,name='esignin'),
    path('join/',signup,name='join'),
    path('login/',signin,name='signin'),
    path('', include('board.urls', namespace='board')),
    path('logout/',auth_views.logout,{'next_page':'/'},name='logout'),
]

board/urls.py
from django.urls import path

from board import views

app_name = 'board'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('detail/<int:id>/', views.post_detail, name='post_detail'),
    path('new',views.post_create,name='post_create'),
    path('update/<int:id>', views.post_update, name='post_update'),
    path('delete/<int:id>', views.post_delete, name='post_delete'),
    path('create/<int:id>', views.post_create,name='post_create'),
]

Account/models.py
from django.db import models
# Create your models here.:

board/models.py
from django.conf import settings
from django.db import models

# Create your models here.

class Post(models.Model):
    name = models.CharField(max_length=150)
    title = models.CharField(max_length=100, verbose_name='주소를 입력하세요')
    detail = models.CharField(max_length=100,verbose_name='주소를 입력하세요')
    content = models.TextField(verbose_name='계좌번호와 희망 요금을 입력하세요')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ['-id']
    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('Post',on_delete=models.CASCADE,)
    author = models.CharField(max_length=20)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Account/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password','first_name','last_name',]
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'15자 이내로 입력 가능합니다.'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password' : forms.PasswordInput(attrs={'class': 'form-control'}),
            'first_name' : forms.TextInput(attrs={'class':'form-control','placeholder':'주소',}),
            'last_name' : forms.TextInput(attrs={'class':'form-control','placeholder':'상세주소',}),
        }
        labels = {
            'username' : '아이디',
            'email' : '이메일',
            'password' : '패스워드',
            'first_name' : '주소',
            'last_name' : '상세주소',
        }
        
class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {
                'username':forms.TextInput(attrs={'placeholder':'Username','class':'form-control'}),
                'password':forms.PasswordInput(attrs={'placeholder':'Password','class':'form-control'}),
        }

Account/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .forms import UserForm,LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate
from django.template import RequestContext

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            new_user = User.objects.create_user(**form.cleaned_data)
            login(request, new_user)
            return redirect('board:post_list')

        else:
            return HttpResponseRedirect('/error/')

    else:
        form = UserForm()
        return render(request,'Account/adduser.html',{'form':form})
# Create your views here.
def signin(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username,password = password)

        if user is not None:
            login(request,user)
            return redirect('board:post_list')
        else:
            return HttpResponseRedirect('/esignin/')
    else:
        form = LoginForm()
        return render(request,'Account/login.html',{'form':form})

def profile(request):
    return render(request,'Account/profile.html')
def esignin(request):
    return render(request,'Account/esignin.html')
def error(request):
    return render(request,'Account/error.html')

board/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Post
# Create your views here.

def post_list(request):

    qs = Post.objects.all()
    q = request.GET.get('q','')
    if q:
        qs = qs.filter(title__icontains=q)

    response = render(request, 'board/post_list.html', {
        'post_list' : qs,
        'q' : q,

    })
    return response

def post_detail(request,id):
    post = get_object_or_404(Post,id=id)

    return render(request,'board/post_detail.html',{
        'post' : post
    })

@login_required
def post_create(request):
    ctx = {}
    if request.method == 'POST':
        title = request.POST.get('title')
        detail = request.POST.get('detail')
        content = request.POST.get('content')

        if title and content:
            post = Post.objects.create(
                title=title,
                detail = detail,
                content=content,
                name = request.user.get_username()
            )
            url = reverse('board:post_detail', kwargs={
                'id': post.id,
            })
            return redirect(url)
        else:
            error_msg={}
            if not title:
                error_msg.update({'title':'제목을 입력해주세요'})
            if not content:
                error_msg.update({'content': '내용을 입력해주세요'})
            ctx.update({'error':error_msg, })

    return render(request,'board/post_create.html', ctx)

@login_required
def post_delete(request,id):
    post = get_object_or_404(Post, id=id)
    post.delete()
    return redirect('board:post_list')

@login_required

def post_update(request,id):
    post = get_object_or_404(Post, id=id)
    title = post.title
    detail = post.detail
    content= post.content
    if request.method == 'POST':
        post.title = request.POST.get('title')
        post.detail = request.POST.get('detail')
        post.content = request.POST.get('content')
        post.save()
        url = reverse('board:post_detail', kwargs={
            'id': post.id,
        })
        return redirect(url)

    ctx = {
        'post': post,
        'title': title,
        'detail':detail,
        'content': content,
    }
    return render(request, 'board/post_create.html', ctx)

Hackathon/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Monoton" rel="stylesheet">
  <meta charset="UTF-8">
  <title>Parking For All</title>
</head>
<body>

	<h1 style="padding-top:100px; text-align:center; font-family: 'Monoton', cursive;">PARKING    FOR    ALL</h1>



  {% block content %}
  {% endblock %}
  <hr/>
  &copy; 2018 ParkingForAll

</body>

</html>

board/templates/board/layout.html
{% extends 'layout.html' %}

board/templates/board/post_create.html
{% extends 'board/layout.html' %}


{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="robots" content="noindex, nofollow">

    <title>Basic Register Page - Bootsnipp.com</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <style type="text/css">
        </style>
    <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        window.alert = function(){};
        var defaultCSS = document.getElementById('bootstrap-css');
        function changeCSS(css){
            if(css) $('head > link').filter(':first').replaceWith('<link rel="stylesheet" href="'+ css +'" type="text/css" />'); 
            else $('head > link').filter(':first').replaceWith(defaultCSS); 
        }
        $( document ).ready(function() {
          var iframe_height = parseInt($('html').height()); 
          window.parent.postMessage( iframe_height, 'https://bootsnipp.com');
        });
    </script>
</head>
<body>
    <div class="container-fluid">
    <section class="container">
        <form method="post" action="">
                {% csrf_token %}
		<div class="container-page">				
			<div class="col-md-6">

			{% if post %}
    		<h3 class="dark-grey">수정하기</h3>
			{% else %}
			<h3 class="dark-grey">주소와 시간 및  희망 요금을 알려주세요</h3>
			{% endif %}
				<div class="form-group col-lg-6">
                    <label>주소</label>
                    <input type="text" id="sample6_postcode" placeholder="우편번호" class="form-control">
                </div>
                <div class="form-group col-lg-6">
                    <label style="color:white">주소</label><br>
                    <input class="btn btn-primary" type="button" onclick="sample6_execDaumPostcode()" value="우편번호 찾기">
                </div>
                <div class="form-group col-lg-12">
                        <input type="text" name="title" class="form-control" placeholder="주소" id="title" maxlength="30" />
                </div>
                <div class="form-group col-lg-12">
                        <input type="text" name="detail" class="form-control" placeholder="상세주소" id="detail" maxlength="150" />
                </div>
                <script src="http://dmaps.daum.net/map_js_init/postcode.v2.js"></script>
                {% if error.title %}
                <p style="color: red;">제목을 입력해주세요</p>
                {% endif %}
                <div class="form-group col-lg-12">
                    <label for="content">계좌 및 희망요금 :</label><br>
                    <input type="text" name="content" class="form-control"/><br>
                </div>
                {% if error.content %}
                    <p style="color: red;">내용을 입력해주세요</p>
                    {% endif %}
<script>
    function sample6_execDaumPostcode() {
        new daum.Postcode({
            oncomplete: function(data) {
                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

                // 각 주소의 노출 규칙에 따라 주소를 조합한다.
                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                var fullAddr = ''; // 최종 주소 변수
                var extraAddr = ''; // 조합형 주소 변수

                // 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
                    fullAddr = data.roadAddress;

                } else { // 사용자가 지번 주소를 선택했을 경우(J)
                    fullAddr = data.jibunAddress;
                }

                // 사용자가 선택한 주소가 도로명 타입일때 조합한다.
                if(data.userSelectedType === 'R'){
                    //법정동명이 있을 경우 추가한다.
                    if(data.bname !== ''){
                        extraAddr += data.bname;
                    }
                    // 건물명이 있을 경우 추가한다.
                    if(data.buildingName !== ''){
                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                    }
                    // 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.
                    fullAddr += (extraAddr !== '' ? ' ('+ extraAddr +')' : '');
                }

                // 우편번호와 주소 정보를 해당 필드에 넣는다.
                document.getElementById('sample6_postcode').value = data.zonecode; //5자리 새우편번호 사용
                document.getElementById('title').value = fullAddr;

                // 커서를 상세주소 필드로 이동한다.
                document.getElementById('detail').focus();
            }
        }).open();
    }
</script>
			<br>
			
            <div class="form-group col-lg-6">
                    <label style="color:white">제출</label><br>
                <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </div>
        </form>
    </section>
    
</div>	<script type="text/javascript">
		</script>
</body>
</html>
{% endblock %}

board/templates/board/post_detail.html
{% extends "board/layout.html" %}

{% block title %}

  {{post.title}}

{% endblock %}
{% block content %}
  <head>
  <style>
    .container{
      text-align: center;

    }
    .options{
      text-align: center;
    }

  </style>

  </head>
{% if user.is_active %}

<p align="right" style="font-family: 'Montserrat', sans-serif;">Welcome, {{user.username}}　　</p>
<p align="right">
<button type="submit"><a href="{% url 'logout' %}">로그아웃</a></button>
</p>

{% else %}
{% if form.errors %}
<p>ID나 PW가 불일치합니다.</p>
{% endif %}

<p align="right">
<button type="submit"><a href="{% url 'signin' %}">로그인</a></button>
</p>
{% endif %}
  <div class = "container">
  <h2>{{post.title}}<br/>{{ post.detail }}</h2>
    <div>
      {{post.content|linebreaks}}

    </div>


  <hr/>


  </div>
  <div class="options">
    <a href="{% url 'board:post_list' %}" class="waves-effect waves-light btn">목록으로</a>
	{% if user.is_active %}
	<a href="{% url 'board:post_update' id=post.id %}" class="waves-effect waves-light btn">수정하기</a>
    <a href="{% url 'board:post_delete' id=post.id %}" class="waves-effect waves-light btn">삭제하기</a>
	{% endif %}

  </div>

{% endblock %}

board/templates/board/post_list.html
{% extends "board/layout.html" %}
<head>
	<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
	<style>
	.col_centered{
		margin:0 auto;
		text-align:center;
		float:noen;
	}
	</style>
</head>

{% block content %}
{% if user.is_active %}

<p align="right" style="font-family: 'Montserrat', sans-serif;">Welcome, {{user.username}}　　</p>
<p align="right">
<button type="submit"><a href="{% url 'logout' %}">로그아웃</a></button>
<button type="submit"><a href="{% url 'board:post_create' %}">글쓰기</a></button>
</p>
{% else %}
<p align="right">
<button type="submit"><a href="{% url 'signin' %}">로그인</a></button>
<button type="submit"><a href="{% url 'join' %}">회원가입</a></button>
</p>
{% endif %}
<form action="" method="get">
	<div class="input-group col_centered" align="center">
  	<input align="center" type="text" class="form-control" aria-describedby="basic-addon2" name="q" value="{{q}}">
	<div class="input-group-append">
  		<button class="btn btn-outline-secondary" type="submit">Button</button>
  	</div>
  </div>
</form>


<ul class="list-group">
    {%for post in post_list%}
    <li class="list-group-item" style="padding-left:20px;padding-right:20px;">
      <a href="{% url "board:post_detail" post.id %}">
        {{post.title}} {{ post.detail }}
      </a>
      <small>by <a href ="{% url 'profile' %} ">{{post.name}}</a></small>
      <small>at {{post.updated_at}}</small>

    </li>

    {%endfor%}

  </ul>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock %}